"""layouts.py: shapes drawn to their figures, the same for the same seed."""
import math
import os
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import geodata  # noqa: E402
import layouts  # noqa: E402
import nodeset  # noqa: E402
import store  # noqa: E402


def metres(data):
    return {name: geodata.synthetic_xy(n["lat"], n["lon"]) for name, n in data["nodes"].items()}


def nearest(points):
    return [min(math.dist(p, q) for q in points if q is not p) for p in points]


def test_a_hex_layout_puts_every_node_its_spacing_from_its_neighbours():
    data = layouts.generate("hex", spacing_m=500, radius_m=1000)
    at = metres(data)
    assert len(at) == 19                    # the centre, and rings at 500, 866 and 1000 m
    assert all(math.hypot(*p) <= 1000 + 1e-6 for p in at.values())
    assert nearest(list(at.values())) == pytest.approx([500.0] * 19)
    assert list(at) == ["n%03d" % i for i in range(1, 20)]
    ids = [n["id"] for n in data["nodes"].values()]
    assert ids == list(range(1, 20))


def test_jitter_moves_a_node_no_further_than_asked():
    still = metres(layouts.generate("hex", spacing_m=500, radius_m=1000))
    shaken = metres(layouts.generate("hex", spacing_m=500, radius_m=1000, jitter_m=40, seed=3))
    assert len(shaken) == len(still)
    moved = [min(math.dist(p, q) for q in still.values()) for p in shaken.values()]
    assert max(moved) <= 40 + 1e-6 and max(moved) > 0


def test_a_disc_holds_its_n_within_its_radius_the_same_for_one_seed():
    a = layouts.generate("disc", n=40, radius_m=2000, seed=7)
    assert len(a["nodes"]) == 40
    assert all(math.hypot(*p) <= 2000 for p in metres(a).values())
    assert a == layouts.generate("disc", n=40, radius_m=2000, seed=7)
    assert a != layouts.generate("disc", n=40, radius_m=2000, seed=8)


def test_clusters_with_a_bridge_are_a_dumbbell():
    data = layouts.generate("clusters", clusters=2, per=10, spread_m=200, apart_m=3000,
                            bridge=1, seed=2)
    at = metres(data)
    assert len(at) == 21
    on_line = [p for p in at.values() if abs(p[1]) < 1e-9 and abs(p[0]) < 1e-9]
    assert len(on_line) == 1                # the bridge, halfway between the crowds
    crowds = [p for p in at.values() if p not in on_line]
    assert all(min(math.dist(p, (-1500, 0)), math.dist(p, (1500, 0))) <= 200 for p in crowds)


def test_a_share_of_the_nodes_is_transport_and_every_node_gets_the_tags():
    data = layouts.generate("disc", n=30, radius_m=1000, transport_share=0.2,
                            tags=["berlinmesh"], seed=5)
    tags = [n["tags"] for n in data["nodes"].values()]
    assert sum("transport" in t for t in tags) == 6
    assert all("berlinmesh" in t for t in tags)
    with pytest.raises(store.StoreError):
        layouts.generate("disc", transport_share=1.5)
    with pytest.raises(store.StoreError):
        layouts.generate("ring")


def test_the_command_writes_a_nodeset_that_says_what_wrote_it(tmp_path, monkeypatch):
    monkeypatch.setattr(store, "NODESETS_DIR", str(tmp_path))
    assert layouts.main(["hex", "honey", "--spacing-m", "400", "--radius-m", "800"]) == 0
    ns = nodeset.load("honey")
    assert len(ns.nodes) == 19
    assert "Generated by layouts.py: hex, 400 m apart" in (nodeset.comment_of(ns.path) or "")
    with pytest.raises(SystemExit):
        layouts.main(["hex", "honey"])      # there already, and no --force
    assert layouts.main(["hex", "honey", "--force", "--spacing-m", "800"]) == 0
